// Generated by CoffeeScript 1.7.1
(function() {
  var app, data, express, io, server, tables;

  express = require("express");

  app = express();

  server = require("http").createServer(app);

  io = require("socket.io")(server);

  app.use(express["static"]("" + __dirname + "/../public"));

  tables = [
    {
      id: "og4",
      label: "4. OG"
    }, {
      id: "og3",
      label: "3. OG"
    }, {
      id: "og2",
      label: "2. OG"
    }, {
      id: "og1",
      label: "1. OG"
    }
  ];

  data = function() {
    var table, _i, _len, _ref;
    for (_i = 0, _len = tables.length; _i < _len; _i++) {
      table = tables[_i];
      table.player_ids = Object.keys((_ref = io.sockets.adapter.rooms[table.id]) != null ? _ref : {});
      table.player_count = table.player_ids.length;
      table.fill_level = 100 * table.player_count / 4;
    }
    return tables;
  };

  io.on("connect", function(socket) {
    socket.emit("id", socket.id);
    socket.emit("data", data());
    socket.on("join", function(id) {
      socket.join(id);
      return io.emit("data", data());
    });
    socket.on("leave", function(id) {
      socket.leave(id);
      return io.emit("data", data());
    });
    return socket.on("disconnect", function() {
      return io.emit("data", data());
    });
  });

  server.listen(3000);

}).call(this);
